[project]
name = "image-embedding-inference"
version = "0.0.1"
description = "Image Embedding Inference"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "gunicorn>=23.0.0",
    "pillow",
    "onnxruntime",
    "uvicorn>=0.34.0",
]
